### PR TITLE
Preserving selection on focused inputs

### PR DESCRIPTION
**Pull request by aishikaty**
This will allow you to dispatch actions while inputing text and not writing at the end of the input.

BTW: I love this library!

### CODE REVIEW

**Comment by danculley** [comment]
Thanks! And doubly thanks for including a pull request! 

I'd like to better understand the use case. There may be other form state that should be preserved that we haven't thought of, so it would be good to do this in an extensible way.

Could you put together a plunker / fiddle / etc. with the use case you are thinking of?

**Comment by aishikaty** [comment]
Here is the use case (try to write Hello before World):
https://plnkr.co/edit/8VmhyDHXfMR3vyPa2DVs?p=preview
```javascript
(function main(h, component) {
  var initialState = { value: "World" };
  var view = function view(state, dispatch) { 
    return h('div', {}, 
      h('input', {
        id: 'input1',
        oninput: function() {
          dispatch({ type: 'SET_VALUE', value: this.value })
        },
        value: state.value
      }),
      state.value
    )
  };
  
  var reducer = function reducer(state, action) {
    switch (action.type) {
      case 'SET_VALUE': return { value: action.value }
    }
  }

  var myComponent = component(initialState, view, reducer);
  
  document.addEventListener('DOMContentLoaded', function() {
    myComponent(document.getElementById('root'))
  })
})(realDOM.h, realDOM.component);
```

**Comment by danculley** [comment]
Thanks! That was super helpful and got me thinking more about what else should get preserved. Ultimately, I decided it would make sense to preserve `selectionStart`, `selectionEnd`, `selectionDirection`, `scrollTop`, and `scrollLeft` for all elements with an `id` property. Obviously some of these won't apply sometimes, but copying them as undefined doesn't really seem to hurt anything. This resolves your bug as well.

https://plnkr.co/edit/J9WMGYQrvpGtqPAUmRdG

**Comment by aishikaty** [comment]
Nice, thanks.

**Pull request closed without merging**
